### ISSUE TITLE
Deploying outputs to GitHub Pages

### ISSUE THREAD

**Issue by SnO2WMaN** [leanprover/verso#129]
When I start to try this project, I spent a time because I didn't installed lualatex in my environment and also results are compressed as zip file. Why not deploy to GitHub Pages? 

I can update `workflows/ci.yml` to setup to deploy, so if you want to I'll send PR.

If this restrict is because of leanprover organization policy, I apologize.

**Comment by david-christiansen** [comment]
The current docs that the project generates for itself are so woefully incomplete that I don't think they're particularly useful to host anywhere. As that changes, I'll host them as part of the overall Lean documentation (which uses a different host).

Thanks for the offer, though!

You should be able to run Verso just fine without having `lualatex` installed if you don't try to generate PDFs. Where is it getting stuck for you?

**Comment by SnO2WMaN** [comment]
Currently, doc generation in my local env is fine, I was simply a bit confused to stuck about installing lualatex and etc. Thanks for replying.
