### ISSUE TITLE
Create tags for stable releases

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/verso#166]
Would it be possible to start creating tags for versions using stable releases? I know that Subverso makes it unnecessary for Verso to be in sync with the code being documented, but versions working on stable lean releases would be handy for:

* Writing and sharing Verso extensions
* Students who only have disk space / confusion budget for a single lean installation.

Hopefully this amounts to checking out an old version on the appropriate nightly, bumping to the subsequent release in a branch, and pushing a tag.

**Comment by david-christiansen** [comment]
Yes, this is definitely possible. I'll add it to our Lean release checklist!

**Comment by david-christiansen** [comment]
All right, I just pushed a tag from the last Lean release. Does it meet your needs, or is there some other bit of useful setup that's still missing?

**Comment by eric-wieser** [comment]
Thanks for the speedy action! My current needs are a tag for 4.10.0, but I am happy for you to ignore these needs and have me update to 4.11.0 or the upcoming 4.12.0 instead :).

**Comment by david-christiansen** [comment]
I just ran a quick bisect and stuck `v4.10.0` on the last commit that worked with that release.
